In [1]:
#install kaggle
!pip install -q kaggle

In [2]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"chandana9","key":"585c1fa671c9b26c36b929f3bc5f5d61"}'}

In [3]:
#create a kaggle folder
! mkdir ~/.kaggle

In [4]:
#copy the kaggle folder to folder created
! cp kaggle.json ~/.kaggle/

In [5]:
#permission from json to act
! chmod 600 ~/.kaggle/kaggle.json

In [7]:
#listing the datasets in kaggle
! kaggle datasets list

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.4)
ref                                                         title                                              size  lastUpdated          downloadCount
----------------------------------------------------------  ------------------------------------------------  -----  -------------------  -------------
gpreda/reddit-vaccine-myths                                 Reddit Vaccine Myths                              233KB  2021-08-22 13:49:51          11098
crowww/a-large-scale-fish-dataset                           A Large Scale Fish Dataset                          3GB  2021-04-28 17:03:01           6785
imsparsh/musicnet-dataset                                   MusicNet Dataset                                   22GB  2021-02-18 14:12:19           2618
promptcloud/careerbuilder-job-listing-2020                  Careerbuilder Job Listing 2020                     42MB  2021-03-05 06:59:52           1691
dhruvildave/wikibooks-dataset                               Wikibooks Dataset                                   2GB  2021-07-03 18:37:20           2711
mathurinache/twitter-edge-nodes                             Twitter Edge Nodes                                342MB  2021-03-08 06:43:04            813
fatiimaezzahra/famous-iconic-women                          Famous Iconic Women                               838MB  2021-02-28 14:56:00           1174
nickuzmenkov/nih-chest-xrays-tfrecords                      NIH Chest X-rays TFRecords                         11GB  2021-03-09 04:49:23            989
alsgroup/end-als                                            End ALS Kaggle Challenge                           12GB  2021-04-08 12:16:37            846
simiotic/github-code-snippets                               GitHub Code Snippets                                7GB  2021-03-03 11:34:39            294
coloradokb/dandelionimages                                  DandelionImages                                     4GB  2021-02-19 20:03:47            726
mathurinache/the-lj-speech-dataset                          The LJ Speech Dataset                               3GB  2021-02-15 09:19:54            301
imsparsh/accentdb-core-extended                             AccentDB - Core & Extended                          6GB  2021-02-17 14:22:54            135
stuartjames/lights                                          LightS: Light Specularity Dataset                  18GB  2021-02-18 14:32:26            126
nickuzmenkov/ranzcr-clip-kfold-tfrecords                    RANZCR CLiP KFold TFRecords                         2GB  2021-02-21 13:29:51            123
landrykezebou/lvzhdr-tone-mapping-benchmark-dataset-tmonet  LVZ-HDR Tone Mapping Benchmark Dataset (TMO-Net)   24GB  2021-03-01 05:03:40            175
datasnaek/youtube-new                                       Trending YouTube Video Statistics                 201MB  2019-06-03 00:56:47         147124
zynicide/wine-reviews                                       Wine Reviews                                       51MB  2017-11-27 17:08:04         142414
residentmario/ramen-ratings                                 Ramen Ratings                                      40KB  2018-01-11 16:04:39          26029
datasnaek/chess                                             Chess Game Dataset (Lichess)                        3MB  2017-09-04 03:09:09          21006

In [8]:
!kaggle datasets download -d new-york-city/nyc-parking-tickets

Downloading nyc-parking-tickets.zip to /content
100% 2.02G/2.02G [00:57<00:00, 55.5MB/s]
100% 2.02G/2.02G [00:57<00:00, 37.6MB/s]

In [9]:
!unzip nyc-parking-tickets.zip

Archive:  nyc-parking-tickets.zip
  inflating: Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv
  inflating: Parking_Violations_Issued_-_Fiscal_Year_2015.csv
  inflating: Parking_Violations_Issued_-_Fiscal_Year_2016.csv
  inflating: Parking_Violations_Issued_-_Fiscal_Year_2017.csv

In [10]:
import pandas as pd
nyc_parkingdata = pd.read_csv("/content/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (17,18,20,21,22,23,29,30,31,32,36,38,39) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [11]:
nyc_parkingdata.describe

<bound method NDFrame.describe of          Summons Number Plate ID Registration State  ... BIN BBL  NTA
0            1283294138  GBB9093                 NY  ... NaN NaN  NaN
1            1283294151  62416MB                 NY  ... NaN NaN  NaN
2            1283294163  78755JZ                 NY  ... NaN NaN  NaN
3            1283294175  63009MA                 NY  ... NaN NaN  NaN
4            1283294187  91648MC                 NY  ... NaN NaN  NaN
...                 ...      ...                ...  ...  ..  ..  ...
9100273      8006150199  16088MC                 NY  ... NaN NaN  NaN
9100274      8006150217  94008JW                 NY  ... NaN NaN  NaN
9100275      8006150242  FWG3729                 NY  ... NaN NaN  NaN
9100276      8006150254   193YUR                 CT  ... NaN NaN  NaN
9100277      8006150278  FPN7411                 NY  ... NaN NaN  NaN

[9100278 rows x 51 columns]>

In [12]:
nyc_parkingdata.head

<bound method NDFrame.head of          Summons Number Plate ID Registration State  ... BIN BBL  NTA
0            1283294138  GBB9093                 NY  ... NaN NaN  NaN
1            1283294151  62416MB                 NY  ... NaN NaN  NaN
2            1283294163  78755JZ                 NY  ... NaN NaN  NaN
3            1283294175  63009MA                 NY  ... NaN NaN  NaN
4            1283294187  91648MC                 NY  ... NaN NaN  NaN
...                 ...      ...                ...  ...  ..  ..  ...
9100273      8006150199  16088MC                 NY  ... NaN NaN  NaN
9100274      8006150217  94008JW                 NY  ... NaN NaN  NaN
9100275      8006150242  FWG3729                 NY  ... NaN NaN  NaN
9100276      8006150254   193YUR                 CT  ... NaN NaN  NaN
9100277      8006150278  FPN7411                 NY  ... NaN NaN  NaN

[9100278 rows x 51 columns]>

In [13]:
nyc_parkingdata.columns

Index(['Summons Number', 'Plate ID', 'Registration State', 'Plate Type',
       'Issue Date', 'Violation Code', 'Vehicle Body Type', 'Vehicle Make',
       'Issuing Agency', 'Street Code1', 'Street Code2', 'Street Code3',
       'Vehicle Expiration Date', 'Violation Location', 'Violation Precinct',
       'Issuer Precinct', 'Issuer Code', 'Issuer Command', 'Issuer Squad',
       'Violation Time', 'Time First Observed', 'Violation County',
       'Violation In Front Of Or Opposite', 'House Number', 'Street Name',
       'Intersecting Street', 'Date First Observed', 'Law Section',
       'Sub Division', 'Violation Legal Code', 'Days Parking In Effect    ',
       'From Hours In Effect', 'To Hours In Effect', 'Vehicle Color',
       'Unregistered Vehicle?', 'Vehicle Year', 'Meter Number',
       'Feet From Curb', 'Violation Post Code', 'Violation Description',
       'No Standing or Stopping Violation', 'Hydrant Violation',
       'Double Parking Violation', 'Latitude', 'Longitude', 'Community Board',
       'Community Council ', 'Census Tract', 'BIN', 'BBL', 'NTA'],
      dtype='object')

In [14]:
# creating a utility file

%%writefile testutility.py
import logging
import os
import subprocess
import yaml
import pandas as pd
import datetime
import gc
import re


################
# File Reading #
################

def read_config_file(filepath):
    with open(filepath, 'r') as stream:
        try:
            return yaml.safe_load(stream)
        except yaml.YAMLError as exc:
            logging.error(exc)


def replacer(string, char):
    pattern = char + '{2,}'
    string = re.sub(pattern, char, string)
    return string


def col_header_val(df, table_config):
    """ replace whitespaces in the column  and standardized column names """
    df.columns = df.columns.str.lower()
    df.columns = df.columns.str.replace('[^\w]', '_', regex=True)
    df.columns = list(map(lambda x: x.strip('_'), list(df.columns)))
    df.columns = list(map(lambda x: replacer(x, '_'), list(df.columns)))
    expected_col = list(map(lambda x: x.lower(), table_config['columns']))
    expected_col.sort()
    df.columns = list(map(lambda x: x.lower(), list(df.columns)))
    df = df.reindex(sorted(df.columns), axis=1)
    if len(df.columns) == len(expected_col) and list(expected_col) == list(df.columns):
        print("column name and column length validation passed")
        return 1
    else:
        print("column name and column length validation failed")
        mismatched_columns_file = list(set(df.columns).difference(expected_col))
        print("Following File columns are not in the YAML file", mismatched_columns_file)
        missing_YAML_file = list(set(expected_col).difference(df.columns))
        print("Following YAML columns are not in the file uploaded", missing_YAML_file)
        logging.info(f'df columns: {df.columns}')
        logging.info(f'expected columns: {expected_col}')
        return 0

Overwriting testutility.py

In [13]:
# createing a yaml file

%%writefile file.yaml
file_type: csv
dataset_name: testfile
file_name: Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_
table_name: edsurv
inbound_delimeter: ","
outbound_delimeter: "|"
skip_leading_rows: 1
columns:
    -Summons Number
    -Plate ID
    -Registration State
    -Plate Type
    -Issue Date
    -Violation Code
    -Vehicle Body Type
    -Vehicle Make
    -Issuing Agency
    -Street Code1
    -Street Code2
    -Street Code3
    -Vehicle Expiration Date
    -Violation Location
    -Violation Precinct
    -Issuer Precinct
    -Issuer Code
    -Issuer Command
    -Issuer Squad
    -Violation Time
    -Time First Observed
    -Violation County
    -Violation In Front Of Or Opposite
    -House Number
    -Street Name
    -Intersecting Street-Date First Observed
    -Law Section
    -Sub Division
    -Violation Legal Code
    -Days Parking In Effect    
    -From Hours In Effect
    -To Hours In Effect
    -Vehicle Color
    -Unregistered Vehicle?
    -Vehicle Year
    -Meter Number
    -Feet From Curb-Violation Post Code
    -Violation Description
    -No Standing or Stopping Violation
    -Hydrant Violation
    -Double Parking Violation
    -Latitude
    -Longitude
    -Community Board
    -Community Council 
    -Census Tract
    -BIN
    -BBL
    -NTA

Overwriting file.yaml

In [2]:
# Read config file
import testutility as util
config_data = util.read_config_file("file.yaml")

In [11]:
config_data['file_type']

'csv'

In [12]:
config_data

{'columns': '-Summons Number -Plate ID -Registration State -Plate Type -Issue Date -Violation Code -Vehicle Body Type -Vehicle Make -Issuing Agency -Street Code1 -Street Code2 -Street Code3 -Vehicle Expiration Date -Violation Location -Violation Precinct -Issuer Precinct -Issuer Code -Issuer Command -Issuer Squad -Violation Time -Time First Observed -Violation County -Violation In Front Of Or Opposite -House Number -Street Name -Intersecting Street-Date First Observed -Law Section -Sub Division -Violation Legal Code -Days Parking In Effect -From Hours In Effect -To Hours In Effect -Vehicle Color -Unregistered Vehicle? -Vehicle Year -Meter Number -Feet From Curb-Violation Post Code -Violation Description -No Standing or Stopping Violation -Hydrant Violation -Double Parking Violation -Latitude -Longitude -Community Board -Community Council -Census Tract -BIN -BBL -NTA',
 'dataset_name': 'testfile',
 'file_name': 'Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_',
 'file_type': 'csv',
 'inbound_delimeter': ',',
 'outbound_delimeter': '|',
 'skip_leading_rows': 1,
 'table_name': 'edsurv'}

In [3]:
import pandas as pd
df_sample = pd.read_csv("Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv",delimiter=',')
df_sample.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (17,18,20,21,22,23,29,30,31,32,36,38,39) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

   Summons Number Plate ID Registration State  ... BIN BBL  NTA
0      1283294138  GBB9093                 NY  ... NaN NaN  NaN
1      1283294151  62416MB                 NY  ... NaN NaN  NaN
2      1283294163  78755JZ                 NY  ... NaN NaN  NaN
3      1283294175  63009MA                 NY  ... NaN NaN  NaN
4      1283294187  91648MC                 NY  ... NaN NaN  NaN

[5 rows x 51 columns]

In [3]:
import pandas as pd 
file_type=config_data['file_type']
source_file="./"+config_data['file_name'] + f'.{file_type}'

print(source_file)

data=pd.read_csv(source_file,config_data['inbound_delimeter'])
print("New dataset:", data)

./Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (17,18,20,21,22,23,29,30,31,32,36,38,39) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

New dataset:          Summons Number Plate ID Registration State  ... BIN BBL  NTA
0            1283294138  GBB9093                 NY  ... NaN NaN  NaN
1            1283294151  62416MB                 NY  ... NaN NaN  NaN
2            1283294163  78755JZ                 NY  ... NaN NaN  NaN
3            1283294175  63009MA                 NY  ... NaN NaN  NaN
4            1283294187  91648MC                 NY  ... NaN NaN  NaN
...                 ...      ...                ...  ...  ..  ..  ...
9100273      8006150199  16088MC                 NY  ... NaN NaN  NaN
9100274      8006150217  94008JW                 NY  ... NaN NaN  NaN
9100275      8006150242  FWG3729                 NY  ... NaN NaN  NaN
9100276      8006150254   193YUR                 CT  ... NaN NaN  NaN
9100277      8006150278  FPN7411                 NY  ... NaN NaN  NaN

[9100278 rows x 51 columns]

In [4]:

#validate the header of the file
util.col_header_val(data,config_data)

column name and column length validation failed
Following File columns are not in the YAML file ['date_first_observed', 'violation_in_front_of_or_opposite', 'no_standing_or_stopping_violation', 'street_code1', 'street_name', 'vehicle_body_type', 'intersecting_street', 'community_council', 'violation_post_code', 'longitude', 'to_hours_in_effect', 'violation_legal_code', 'violation_time', 'vehicle_year', 'plate_type', 'vehicle_make', 'feet_from_curb', 'house_number', 'meter_number', 'census_tract', 'street_code2', 'bbl', 'unregistered_vehicle', 'vehicle_expiration_date', 'violation_code', 'days_parking_in_effect', 'violation_county', 'issuer_command', 'vehicle_color', 'hydrant_violation', 'issuer_precinct', 'issuer_squad', 'violation_location', 'from_hours_in_effect', 'time_first_observed', 'bin', 'plate_id', 'double_parking_violation', 'latitude', 'issue_date', 'sub_division', 'nta', 'summons_number', 'issuing_agency', 'violation_precinct', 'community_board', 'registration_state', 'street_code3', 'law_section', 'issuer_code', 'violation_description']
Following YAML columns are not in the file uploaded ['p', 'r', 'f', 'w', 'x', 'm', 'q', 'y', 'e', 'o', 'c', 'i', 'k', 'b', 'n', 'l', 's', 'd', '2', '-', 'g', 'a', '?', '1', 'u', ' ', 'v', 'h', 't', '3']

0

In [5]:
print("columns of files are:", data.columns)
print("columns of YAML are:",config_data['columns'])

columns of files are: Index(['summons_number', 'plate_id', 'registration_state', 'plate_type',
       'issue_date', 'violation_code', 'vehicle_body_type', 'vehicle_make',
       'issuing_agency', 'street_code1', 'street_code2', 'street_code3',
       'vehicle_expiration_date', 'violation_location', 'violation_precinct',
       'issuer_precinct', 'issuer_code', 'issuer_command', 'issuer_squad',
       'violation_time', 'time_first_observed', 'violation_county',
       'violation_in_front_of_or_opposite', 'house_number', 'street_name',
       'intersecting_street', 'date_first_observed', 'law_section',
       'sub_division', 'violation_legal_code', 'days_parking_in_effect',
       'from_hours_in_effect', 'to_hours_in_effect', 'vehicle_color',
       'unregistered_vehicle', 'vehicle_year', 'meter_number',
       'feet_from_curb', 'violation_post_code', 'violation_description',
       'no_standing_or_stopping_violation', 'hydrant_violation',
       'double_parking_violation', 'latitude', 'longitude', 'community_board',
       'community_council', 'census_tract', 'bin', 'bbl', 'nta'],
      dtype='object')
columns of YAML are: -Summons Number -Plate ID -Registration State -Plate Type -Issue Date -Violation Code -Vehicle Body Type -Vehicle Make -Issuing Agency -Street Code1 -Street Code2 -Street Code3 -Vehicle Expiration Date -Violation Location -Violation Precinct -Issuer Precinct -Issuer Code -Issuer Command -Issuer Squad -Violation Time -Time First Observed -Violation County -Violation In Front Of Or Opposite -House Number -Street Name -Intersecting Street-Date First Observed -Law Section -Sub Division -Violation Legal Code -Days Parking In Effect -From Hours In Effect -To Hours In Effect -Vehicle Color -Unregistered Vehicle? -Vehicle Year -Meter Number -Feet From Curb-Violation Post Code -Violation Description -No Standing or Stopping Violation -Hydrant Violation -Double Parking Violation -Latitude -Longitude -Community Board -Community Council -Census Tract -BIN -BBL -NTA

In [6]:
if util.col_header_val(data,config_data)==0:
    print("validation failed")
else:
    print("col validation passed")

column name and column length validation failed
Following File columns are not in the YAML file ['date_first_observed', 'violation_in_front_of_or_opposite', 'no_standing_or_stopping_violation', 'street_code1', 'street_name', 'vehicle_body_type', 'intersecting_street', 'community_council', 'violation_post_code', 'longitude', 'to_hours_in_effect', 'violation_legal_code', 'violation_time', 'vehicle_year', 'plate_type', 'vehicle_make', 'feet_from_curb', 'house_number', 'meter_number', 'census_tract', 'street_code2', 'bbl', 'unregistered_vehicle', 'vehicle_expiration_date', 'violation_code', 'days_parking_in_effect', 'violation_county', 'issuer_command', 'vehicle_color', 'hydrant_violation', 'issuer_precinct', 'issuer_squad', 'violation_location', 'from_hours_in_effect', 'time_first_observed', 'bin', 'plate_id', 'double_parking_violation', 'latitude', 'issue_date', 'sub_division', 'nta', 'summons_number', 'issuing_agency', 'violation_precinct', 'community_board', 'registration_state', 'street_code3', 'law_section', 'issuer_code', 'violation_description']
Following YAML columns are not in the file uploaded ['p', 'r', 'f', 'w', 'x', 'm', 'q', 'y', 'e', 'o', 'c', 'i', 'k', 'b', 'n', 'l', 's', 'd', '2', '-', 'g', 'a', '?', '1', 'u', ' ', 'v', 'h', 't', '3']
validation failed

In [1]:
import pandas as pd
pd.read_csv("/content/Parking_Violations_Issued_-_Fiscal_Year_2014__August_2013___June_2014_.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (17,18,20,21,22,23,29,30,31,32,36,38,39) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

         Summons Number Plate ID Registration State  ... BIN BBL  NTA
0            1283294138  GBB9093                 NY  ... NaN NaN  NaN
1            1283294151  62416MB                 NY  ... NaN NaN  NaN
2            1283294163  78755JZ                 NY  ... NaN NaN  NaN
3            1283294175  63009MA                 NY  ... NaN NaN  NaN
4            1283294187  91648MC                 NY  ... NaN NaN  NaN
...                 ...      ...                ...  ...  ..  ..  ...
9100273      8006150199  16088MC                 NY  ... NaN NaN  NaN
9100274      8006150217  94008JW                 NY  ... NaN NaN  NaN
9100275      8006150242  FWG3729                 NY  ... NaN NaN  NaN
9100276      8006150254   193YUR                 CT  ... NaN NaN  NaN
9100277      8006150278  FPN7411                 NY  ... NaN NaN  NaN

[9100278 rows x 51 columns]